spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BlueWhale?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tNoDQYvaaDhnxhR3HYw
    accessKeySecret: czOzwjw6iu4VVwW5dlz1jwXvSts3g7
    bucketName: cwx11