

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tomato_mall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: kongshan
    password: zmt20041204
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080


aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tGaGn9F8wnnHh6pgYEg
    accessKeySecret: RASK8I88rzgAkwHNdvJ8Px4pHQYIvU
    bucketName: bluewhalenju

alipay:
  appId: 2021000147690053
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCm/FCqFycDOKTIuGHLk0JhO/xjSbcnZgyyzPxHz1EhwnBOzap5pNtsJ6jQRUmof6ZH9cmT96AsPt7noBgZhJEk730g2tOew+Cr3rAB8Xj4OI293FMitpqESbvF4DOZ0X8GTWfebi41rvBR/KjGEUd6SzulyQLTJ6t9ltFa4tWr9HtbCU73Anwl7+bBU4fhtBr9B/QSXyv7iixxTlO9y7rRwG5WOpLE1LDMepaJ08JoUOd+RxOAkT3T/EiOpmxzJzxrcsJM8+b/oMktVsi3FcGcIinQtBQAEtlUUFopXt2un9SrAmc/Z7kbkitmskhCv3Q5M+CvGAZLNENYn0OVuntrAgMBAAECggEAa2GV/cslq0yhqvHm8aKg7SZGBxNAVHWrdM+c7BDFe5At6H8ZQWBiOgrG5CeqVlC//UZxelWjCtDjRtAMr1wwejAHpzkRHOeZcuyhAp7ly7mSbKViUNBcTPWdaoHirOerZ8IfKUpxLNRydkajwbsa2+nFUbcRufeor/psZqW4AfsL3ho9DwFfa5NcAMoK2zs2U7L29kYiGIlOdoW6+IhpJSuXzmdUCIl+ePV1ItRbJsqcIZU6/nmmrXEfZzHASnHXP/cAoIefrqoufJvEioJ2tzdiqjU/WoXOvynAEP/mYRltQCq0a+KRmL9OiHkYGANibEBFKoMzaRtlXVJvClCiAQKBgQDTPH+7+vxRYpwspsWI1tdMOjVyAqOyF05L8LW+iZNbm8tN1cYuP5zx0RXu9rcqdpkBhDDgwInMVQzE8N6Bm2+9NUGfUMjp2meg3ed+REKRV7XNhyixkDwJNjlUnOqeTL9o0j7LTvTbwaggj/BmCjcw5qi9rA3Pr1hkNThLxYJmcwKBgQDKXzqvTtcKBz8Tl0+Hd0pU/OLFdKJAwGYD4Xg1lDlVaMJpbmHpYXd14TmcWO8e38zfrsF4BkUH5147vfGp8UPUb9YppTq7gOlIuw9CcNauEf4u/J5gM/A4eFQP4ftlFhG0+RSKgIo0qCWsUogmJnt3tdsdsrWrjTC6ccmjeL/hKQKBgGZliGH+i7uD+sLmYRExXBKWkPvgbavSAmFroR5pIGajAg2MGFKpAZJzUZeSPz41WXxTsUHx85p6jAMX5DSdva/Rlir9hTdfaSahCyu5OS+tffLQlxhkG8Y3Y9kxa8Yq3AqbCFeTwbyZhr+qJtXAE/r/hULUmalYjZed+Nk6ODkjAoGAbHQQjTbhQ3ySrzsd4elqKpXEKjHRaoYxpc7Fj2E6QK190ubXDi2vybrEFygKLi+eKhoLkPk7MXsrIzUuN/cWdNjimzrzeN0jKFknWmICixMVd7TmY4QyLvE9i619/rSPFL+P5JHyfznFxs4MLPXeoU8SeJ33glKOVLz6ZOMnYdECgYAtS3GF4bqCdE2vV7VMXZWTxPrBXVCFqsZgA/u0pN14q9gmpmFbSsPdji05s3qnj/tFyvCyTLscpS5IdrbzfegggiE3/XCEDY5KHeLlFVl3St0mF5TzOB+Bq6jOqVdK5suKQS0B5y7NOyOXBaNyWjExQSFRlVA0ciJfa2muXAUeQQ==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAid+RD8n6tghZgI8lJUu2+UZjAGIdk4kgXj0qBt0L8L/p/ZW6BFX3L2XLvIMTu7CnxrXsGJNV5G7G/olj77JjZnXqfuOyikvnZ2BqYVQeHTr3yFxIC4wWqF7lKdcW4yHT5OWXxT2bx6CJjZDn1WIoitF2CX6jyAguWi+zF8AeCfDoW6yS+G5EL6aSxj5IlbfsoqeMLh2Ft9MJ9QECMxKepCb1uyrGjoPhNLBVh7rvvrT/z4noKRuImZz8zKJ43mPF6t99bRsMSzmDZuFdwVYElESxT1TifH4SyLOrFopRz0ewmpQWvUke1ugZZre3yJ+c04oOUWOL/zBsug/mCmPVwwIDAQAB
  notifyUrl: https://ocalhost:8080/api/orders/notify
  serverUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do



